### ISSUE TITLE
Initial import

### ISSUE THREAD

**Issue by chercka** [raytiley/wp-cablecast#7]
This is great Ray, so far having a good experience with this plugin. Thanks!

Have you considered/have any thoughts on the intitial import procedure? I've got a site with about 700 shows and am seeing about 50 shows imported per time the cron job runs. I'm guessing Cablecast is throttling it, which won't be an issue once everything is imported, but makes it a bit iffy to get up and running.

Anywhere to view a sync-log?

**Comment by raytiley** [comment]
@chercka ... Sorry about this. I really need to get on top of github notifications. I never saw this issue before I went to add a new one myself (and I see they are piling up).

Cablecast's default pagination for the show records is 50, but it can be changed via a URL parameter, so we could bump it up.. but you run the risk of really impacting cablecast performance if you request too many records at once.

What I've done on my test system usually is just set the cron interval to 1 minute and then have my system cron hit wordpress cron every minute. So probably combination of increasing the pagination size a bit, but still safe number and then increasing the cron frequency during initial import would be a good approach.

**Comment by chercka** [comment]
Makes sense, thanks!
